CREATE DATABASE IF NOT EXISTS GRUPO_TOPEN;
USE GRUPO_TOPEN;
CREATE TABLE IF NOT EXISTS tb_grupo (RM INT,NOME VARCHAR(255) NOT NULL);
INSERT INTO tb_grupo (RM, NOME) VALUES (333536,'PAULO MARCEL ZACARELLI PIROTTA');
INSERT INTO tb_grupo (RM, NOME) VALUES (333735,'CINTIA FERREIRA DOS SANTOS');
INSERT INTO tb_grupo (RM, NOME) VALUES (334305,'LEANDRO COELHO BATISTA');
INSERT INTO tb_grupo (RM, NOME) VALUES (334432,'MARCUS VINICIUS DA CUNHA SANTOS');
