CREATE DATABASE IF NOT EXISTS GRUPO_TOPEN;

USE GRUPO_TOPEN;

CREATE TABLE IF NOT EXISTS TB_GRUPO
( RM   NUMBER(6),
  NOME VARCHAR(200) NOT NULL);
  
INSERT INTO TB_GRUPO (RM, NOME) VALUES (333536,"PAULO MARCEL ZACARELLI PIROTTA");
INSERT INTO TB_GRUPO (RM, NOME) VALUES (333735,"CINTIA FERREIRA DOS SANTOS");
INSERT INTO TB_GRUPO (RM, NOME) VALUES (334305,"LEANDRO COELHO BATISTA");
INSERT INTO TB_GRUPO (RM, NOME) VALUES (334432,"MARCUS VINICIUS DA CUNHA SANTOS");
